// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify.
// It will be overwritten.

const awsmobile = {
   aws_project_region: 'auth.us-east-1',
   aws_cognito_identity_pool_id: 'us-east-1:d43f18d8-08e1-4444-8ad3-43eb18540540',
   aws_cognito_region: 'auth.us-east-1',
   aws_user_pools_id: 'us-east-1_qRK2JytGV',
   aws_user_pools_web_client_id: '42c32l77mm1hrgd5kklrriqhke',
   oauth: {},
 };
 
 
 export default awsmobile;